spring:
  jackson:
    # Date format string or a fully-qualified date format class name. For instance, 'yyyy-MM-dd HH:mm:ss'
    date-format: "yyyy-MM-dd HH:mm"
    # Locale used for formatting
    time-zone: "GMT+3"
  application:
    name: taskTracker
  mvc:
    format:
      date: yyyy-MM-dd HH:mm
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5438/tasks
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
server:
  port: 8080
frontend:
  host: http://25.68.40.138:5173
  login-page: http://25.68.40.138:5173/task-tracker/auth/login