server:
  port: 8080
spring:
  jackson:
    date-format: "yyyy-MM-dd HH:mm"
    time-zone: "GMT+3"
  application:
    name: TaskService
  mvc:
    format:
      date: yyyy-MM-dd HH:mm
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://109.196.102.221:5432/task_service
    username: postgres
    password: 4WuS-U-dBRtM
    driver-class-name: org.postgresql.Driver
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

